services:
  php:
    build:
      context: ./src
    volumes:
      - ./:/var/www
    ports:
      - 9502:9502
    
  composer:
    image: composer:latest
    volumes:
        - ./:/app
    working_dir: /app
    command: install
    user: "1000"
